airtable:
  base_id: 'appJoAAl0y0Pr2itM'
  table_id: 'tblVnBAyJGFUzRDes'
  fields:
    repo_url: repo_url
    play_url: play_url
    readme_url: readme_url
    ai_guess: ai_guess
    ai_reasoning: ai_reasoning